### ISSUE TITLE
Person API isn't aware of cases

### ISSUE THREAD

**Issue by TimothyJones** [RHoKAustralia/berry-street#21]
Currently a request for `/people` returns all people in the database. Ultimately this will need to be something like `/people/<case ID>`

Also, when there's an improved security/access control model (see #20), we'll need the API to use it to approve or deny requests as appropriate.

**Comment by TimothyJones** [comment]
The `data-model-spike` data model will allow relationships between cases and entities (in the current `master`, all entities are hung off the subjects, meaning it's not possible to have findable network nodes that are not connected to the Subject in some way).

**Comment by abubics** [comment]
Everything is nested under `/cases/${caseId}` now :)
In `data-model-spike`.
